#################################################################################################
#
#    ██╗████████╗███████╗███╗   ███╗██╗   ██╗
#    ██║╚══██╔══╝██╔════╝████╗ ████║╚██╗ ██╔╝
#    ██║   ██║   ███████╗██╔████╔██║ ╚████╔╝
#    ██║   ██║   ╚════██║██║╚██╔╝██║  ╚██╔╝
#    ██║   ██║   ███████║██║ ╚═╝ ██║   ██║
#    ╚═╝   ╚═╝   ╚══════╝╚═╝     ╚═╝   ╚═╝
#
#     █████╗  ██████╗██╗  ██╗██╗███████╗██╗   ██╗███████╗███╗   ███╗███████╗███╗   ██╗████████╗
#    ██╔══██╗██╔════╝██║  ██║██║██╔════╝██║   ██║██╔════╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝
#    ███████║██║     ███████║██║█████╗  ██║   ██║█████╗  ██╔████╔██║█████╗  ██╔██╗ ██║   ██║
#    ██╔══██║██║     ██╔══██║██║██╔══╝  ╚██╗ ██╔╝██╔══╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║
#    ██║  ██║╚██████╗██║  ██║██║███████╗ ╚████╔╝ ███████╗██║ ╚═╝ ██║███████╗██║ ╚████║   ██║
#    ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝  ╚═══╝  ╚══════╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
#
#      Contact: Théo#0001
#      Support: https://itsme.to/discord
#      Documentation: https://docs.itsme.to/itsmyachievement
#
#################################################################################################

time-format: "dd/MM/yyyy"
time-zone: UTC+1